<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>EduLearn</RootNamespace>
    <AssemblyName>EduLearn</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\Admin\Data\**" />
    <Content Remove="Areas\Admin\Data\**" />
    <EmbeddedResource Remove="Areas\Admin\Data\**" />
    <None Remove="Areas\Admin\Data\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Student\Data\" />
    <Folder Include="Areas\Teacher\Data\" />
    <Folder Include="wwwroot\assets\css\" />
    <Folder Include="wwwroot\assets\js\" />
    <Folder Include="wwwroot\Images\home\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\css\customs.css" />
  </ItemGroup>

</Project>
